---
apiVersion: v1
kind: Service
metadata:
  name: mock-server
  namespace: backstage
  labels:
    app: mock-server
spec:
  type: ClusterIP
  selector:
    app: mock-server
  ports:
    - name: http
      port: 4010
      targetPort: 4010
      protocol: TCP
