{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "universal-microservice.secretName" . }}
  {{- with .Values.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "universal-microservice.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type }}
{{- with .Values.secret.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
