---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
spec:
  type: NodePort
  selector:
    app: backstage
  ports:
    - name: http
      port: 7007
      targetPort: 7007
      nodePort: 30000
      protocol: TCP
